# fly.toml app configuration file generated for dark-mountain-646 on 2023-07-04T14:29:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-mountain-646"
primary_region = "sin"

[env]
  PORT = 8080

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
